---
version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./events:/events
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres