---
version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - PORT=4000
      - BINDING=0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ..:/workspace/event-booking:cached
      - ~/Documents/007Dev/00GitLab/.gitconfig:/root/.gitconfig
      - ~/Documents/007Dev/00GitLab/.ssh:/root/.ssh
      - ~/Documents/007Dev/00GitLab/.bash_history:/root/.bash_history
      - ~/Documents/007Dev/00GitLab/.bashrc:/root/.bashrc
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - "database:/var/lib/postgresql/data"

volumes:
  database: